practica2ayd2_rails/config/routes.rb
Rails.application.routes.draw do
  resources :categoria
  resources :detalles
  get 'welcome/index'

    root 'welcome#index'
end

practica2ayd2_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    def id
      sync_with_transaction_state
      read_attribute(self.class.primary_key)
    end

    self.abstract_class = true
end

practica2ayd2_rails/app/models/categoria.rb
class Categoria < ApplicationRecord
end

practica2ayd2_rails/app/models/categorium.rb
class Categorium < ApplicationRecord
    self.table_name = 'ayd2_categoria_201020917'
    self.primary_key = :ayd2_categoria_id
    
    has_many :detalles, foreign_key: "ayd2_categoria_id"
    validates :ayd2_categoria_descripcion,  presence: true, uniqueness: { message: "La categoria ya existe!" } 
    accepts_nested_attributes_for :detalles
end

practica2ayd2_rails/app/models/detalle.rb
class Detalle < ApplicationRecord
    self.table_name = 'ayd2_detalle_201020917'
    self.primary_key = 'ayd2_detalle_id'
    belongs_to :categorium, primary_key: 'ayd2_categoria_id', required: false
end

practica2ayd2_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

practica2ayd2_rails/app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: [:show, :edit, :update, :destroy]

  # GET /categoria
  # GET /categoria.json
  def index
    @categoria = Categorium.all
  end

  # GET /categoria/1
  # GET /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categorium = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria
  # POST /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: 'Categorium was successfully created.' }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1
  # PATCH/PUT /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to @categorium, notice: 'Categorium was successfully updated.' }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1
  # DELETE /categoria/1.json
  def destroy
    @categorium.destroy
    respond_to do |format|
      format.html { redirect_to categoria_url, notice: 'Categorium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categorium_params
      params.require(:categorium).permit(:ayd2_categoria_descripcion)
    end
end

practica2ayd2_rails/app/controllers/detalles_controller.rb
class DetallesController < ApplicationController
  before_action :set_detalle, only: [:show, :edit, :update, :destroy]

  # GET /detalles
  # GET /detalles.json
  def index
    @detalles = Detalle.all
  end

  # GET /detalles/1
  # GET /detalles/1.json
  def show
  end

  # GET /detalles/new
  def new
    @detalle = Detalle.new
    @detalle.ayd2_categoria_id = params[:categoria]
  end

  # GET /detalles/1/edit
  def edit
  end

  # POST /detalles
  # POST /detalles.json
  def create
    @detalle = Detalle.new(detalle_params)
      
    respond_to do |format|
      if @detalle.save
        format.html { redirect_to @detalle, notice: 'Detalle was successfully created.' }
        format.json { render :show, status: :created, location: @detalle }
      else
        format.html { render :new }
        format.json { render json: @detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detalles/1
  # PATCH/PUT /detalles/1.json
  def update
    respond_to do |format|
      if @detalle.update(detalle_params)
        format.html { redirect_to @detalle, notice: 'Detalle was successfully updated.' }
        format.json { render :show, status: :ok, location: @detalle }
      else
        format.html { render :edit }
        format.json { render json: @detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detalles/1
  # DELETE /detalles/1.json
  def destroy
    @detalle.destroy
    respond_to do |format|
      format.html { redirect_to detalles_url, notice: 'Detalle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detalle
      @detalle = Detalle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detalle_params
      params.require(:detalle).permit(:ayd2_detalle_decimal, :ayd2_detalle_descripcion, :ayd2_detalle_date, :ayd2_detalle_datetime, :ayd2_detalle_timestamp, :ayd2_detalle_boolean, :ayd2_categoria_id)
    end
end

practica2ayd2_rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

practica2ayd2_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

practica2ayd2_rails/app/helpers/categoria_helper.rb
module CategoriaHelper
end

practica2ayd2_rails/app/helpers/detalles_helper.rb
module DetallesHelper
end

practica2ayd2_rails/app/helpers/welcome_helper.rb
module WelcomeHelper
end

practica2ayd2_rails/app/views/categoria/_form.html.erb
<%= form_for(categorium) do |f| %>
  <% if categorium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(categorium.errors.count, "error") %> prohibited this categorium from being saved:</h2>

      <ul>
      <% categorium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Descripcion %>
    <%= f.text_field :ayd2_categoria_descripcion %>
  </div>

  <div class="actions">
    <%= f.submit :Guardar %>
  </div>
<% end %>

practica2ayd2_rails/app/views/categoria/edit.html.erb
<h1>Editar Categoria</h1>

<%= render 'form', categorium: @categorium %>

<%= link_to 'Ver', @categorium %> |
<%= link_to 'Regresar', categoria_path %>

practica2ayd2_rails/app/views/categoria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categoria</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria.each do |categorium| %>
      <tr>
        <td><%= categorium.ayd2_categoria_descripcion %></td>
        <td><%= link_to 'Ver', categorium %></td>
        <td><%= link_to 'Editar', edit_categorium_path(categorium) %></td>
        <td><%= link_to 'Eliminar', categorium, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Categoria', new_categorium_path %>

practica2ayd2_rails/app/views/categoria/new.html.erb
<h1>Nueva Categoria</h1>
<%= render 'form', categorium: @categorium %>

<%= link_to 'Back', categoria_path %>

practica2ayd2_rails/app/views/categoria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @categorium.ayd2_categoria_descripcion %>
</p>


<h2>Detalles</h2>
 <table style="width:80%">
  <tr>
    <th>Decimal</th>
    <th>Descripcion</th>
    <th>Date</th>
    <th>DateTime</th>
    <th>Timestamp</th>
    <th>Boolean</th>
    <th>Operaciones</th>
  </tr>
<% @categorium.detalles.each do |detalle| %>
  <tr>
    <td><%= detalle.ayd2_detalle_decimal %></td>
    <td><%= detalle.ayd2_detalle_descripcion %></td>
    <td><%= detalle.ayd2_detalle_date %></td>
    <td><%= detalle.ayd2_detalle_datetime %></td>
    <td><%= detalle.ayd2_detalle_timestamp %></td>
    <td><%= detalle.ayd2_detalle_boolean %></td>
    <td>
        <%= link_to 'Ver', detalle %>
        <%= link_to 'Editar', edit_detalle_path(detalle) %>
        <%= link_to 'Eliminar', detalle, method: :delete, data: { confirm: 'Esta seguro?' } %>
    </td>
  </tr>
<% end %>
</table> 


<%= link_to 'Nuevo Detalle', new_detalle_path(:categoria => @categorium.ayd2_categoria_id) %> |

<%= link_to 'Edit', edit_categorium_path(@categorium) %> |
<%= link_to 'Back', categoria_path %>

practica2ayd2_rails/app/views/detalles/_form.html.erb
<%= form_for(detalle) do |f| %>
  <% if detalle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detalle.errors.count, "error") %> prohibited this detalle from being saved:</h2>

      <ul>
      <% detalle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ayd2_detalle_decimal %>
    <%= f.text_field :ayd2_detalle_decimal %>
  </div>

  <div class="field">
    <%= f.label :ayd2_detalle_descripcion %>
    <%= f.text_field :ayd2_detalle_descripcion %>
  </div>

  <div class="field">
    <%= f.label :ayd2_detalle_date %>
    <%= f.date_select :ayd2_detalle_date %>
  </div>

  <div class="field">
    <%= f.label :ayd2_detalle_datetime %>
    <%= f.datetime_select :ayd2_detalle_datetime %>
  </div>

  <div class="field">
    <%= f.label :ayd2_detalle_timestamp %>
    <%= f.text_field :ayd2_detalle_timestamp %>
  </div>

  <div class="field">
    <%= f.label :ayd2_detalle_boolean %>
    <%= f.check_box :ayd2_detalle_boolean %>
  </div>

  <div class="field">
    <%= f.label :ayd2_categoria_id %>
    <%= f.text_field :ayd2_categoria_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

practica2ayd2_rails/app/views/detalles/edit.html.erb
<h1>Editing Detalle</h1>

<%= render 'form', detalle: @detalle %>

<%= link_to 'Show', @detalle %> |
<%= link_to 'Back', detalles_path %>

practica2ayd2_rails/app/views/detalles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Detalles</h1>

<table>
  <thead>
    <tr>
      <th>decimal</th>
      <th>descripcion</th>
      <th>date</th>
      <th>datetime</th>
      <th>timestamp</th>
      <th>boolean</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @detalles.each do |detalle| %>
      <tr>
        <td><%= detalle.ayd2_detalle_decimal %></td>
        <td><%= detalle.ayd2_detalle_descripcion %></td>
        <td><%= detalle.ayd2_detalle_date %></td>
        <td><%= detalle.ayd2_detalle_datetime %></td>
        <td><%= detalle.ayd2_detalle_timestamp %></td>
        <td><%= detalle.ayd2_detalle_boolean %></td>
        <td><%= link_to 'Regresar a la Categoria', categorium_url(detalle.ayd2_categoria_id ) %></td>
        <td><%= link_to 'Ver', detalle %></td>
        <td><%= link_to 'Editar', edit_detalle_path(detalle) %></td>
        <td><%= link_to 'Destruir', detalle, method: :delete, data: { confirm: 'Esta Seguro' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detalle', new_detalle_path %>

practica2ayd2_rails/app/views/detalles/new.html.erb
<h1>New Detalle</h1>
<%= render 'form', detalle: @detalle %>

<%= link_to 'Back', detalles_path %>

practica2ayd2_rails/app/views/detalles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ayd2 detalle decimal:</strong>
  <%= @detalle.ayd2_detalle_decimal %>
</p>

<p>
  <strong>Ayd2 detalle descripcion:</strong>
  <%= @detalle.ayd2_detalle_descripcion %>
</p>

<p>
  <strong>Ayd2 detalle date:</strong>
  <%= @detalle.ayd2_detalle_date %>
</p>

<p>
  <strong>Ayd2 detalle datetime:</strong>
  <%= @detalle.ayd2_detalle_datetime %>
</p>

<p>
  <strong>Ayd2 detalle timestamp:</strong>
  <%= @detalle.ayd2_detalle_timestamp %>
</p>

<p>
  <strong>Ayd2 detalle boolean:</strong>
  <%= @detalle.ayd2_detalle_boolean %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @detalle.ayd2_categoria_id %>
</p>

<%= link_to 'Edit', edit_detalle_path(@detalle) %> |
<%= link_to 'Back', categorium_path(@detalle.ayd2_categoria_id) %>

practica2ayd2_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practica2ayd2Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

practica2ayd2_rails/app/views/welcome/index.html.erb
<h1>Welcome</h1>
<%= link_to 'Nuevo', new_categorium_path %>